---
- name: Create application deployment directory
  ansible.builtin.file:
    path: "{{ app_dir }}"
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: "0755"

- name: Create docker log directory
  ansible.builtin.file:
    path: "{{ log_dir }}"
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: "0755"
